project:
  type: website

website:
  title: "Monewmetrics"
  navbar:
    left:
      - href: index.qmd
      - text: Blog
        href: posts/index.qmd

format:
  html:
    theme: cosmo
    toc: true
